apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service
spec:
  selector:
    matchLabels:
      app: python-service
  replicas: 3
  template:
    metadata:
      labels:
        app: python-service 
    spec:
      containers:
      - name: python-service
        image: shetty12345/pythonservice:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-service
  name: python-service
  namespace: default
spec:
  type: ClusterIP  
  ports:
    - port: 80
  selector:
    app: python-service
